# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b0878c3c0a1b7a5f7cafcd54a63b2c787f3a7de676ede84075fe751f9dfa290870c537768811da1f7748e65c5dc735d790cb8b618cb4ef4b0c0573b762d48b

test:
  secret_key_base: 1c1ce545bf9a48fd88d62d09ff62519c86b60910fbaa86ace4d45c8b8503e8865b0d7d6355886fd2ac30f4d4c774531fb77a9a54464b0087367dcae0511bebd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
